### ISSUE TITLE
during usage

### ISSUE THREAD

**Issue by shubhamgit1** [Maanas-Verma/pretty_cpp_run#2]
two different names exists - 1) CP_env and 2) pretty_cpp_run

**Comment by Maanas-Verma** [comment]
thanks @shubhamgit1 I will see in this issue

**Comment by Maanas-Verma** [comment]
@shubhamgit1 I have resolved this issue by simply creating a variable that will be going to contain the name of this repo name.
Thanks again to pointing this out.
